POST http://localhost:8080/notifications
Content-Type: application/json

{
  "receiverId": "민경",
  "message": "예약 발송 테스트",
  "eventId": "SCHEDULE_001",
  "channel": "EMAIL",
  "scheduledAt": "2026-05-23T23:42:00"
}

###

PATCH http://localhost:8080/notifications/1/read

###

GET http://localhost:8080/notifications