### 템플릿 알림 생성 - 결제 성공

POST http://localhost:8080/notifications
Content-Type: application/json

{
  "receiverId":"민경",
  "eventId":"PAYMENT_SUCCESS",
  "channel":"EMAIL"
}

###

### 템플릿 알림 생성 - 강의 시작 예약

POST http://localhost:8080/notifications
Content-Type: application/json

{
  "receiverId":"민경",
  "eventId":"LECTURE_START",
  "channel":"EMAIL",
  "scheduledAt":"2026-05-24T16:00:00"
}

###

### 템플릿 알림 생성 - 실패 재시도

POST http://localhost:8080/notifications
Content-Type: application/json

{
  "receiverId":"민경",
  "eventId":"PAYMENT_FAIL",
  "channel":"EMAIL"
}

###

### 전체 조회

GET http://localhost:8080/notifications

###

### 단건 조회

GET http://localhost:8080/notifications/1

###

### 읽음 처리

PATCH http://localhost:8080/notifications/1/read

###

### 수동 재시도

PATCH http://localhost:8080/notifications/3/retry

###

### 사용자별 조회

GET http://localhost:8080/users/%EB%AF%BC%EA%B2%BD/notifications

###

### 읽음 여부 필터 조회

GET http://localhost:8080/users/%EB%AF%BC%EA%B2%BD/notifications?readStatus=true