### 알림 생성 (즉시 발송)

POST http://localhost:8080/notifications
Content-Type: application/json

{
  "receiverId":"민경",
  "message":"결제 완료",
  "eventId":"PAYMENT_001",
  "channel":"EMAIL"
}

###

### 예약 발송 테스트

POST http://localhost:8080/notifications
Content-Type: application/json

{
  "receiverId":"민경",
  "message":"예약 발송 테스트",
  "eventId":"SCHEDULE_001",
  "channel":"EMAIL",
  "scheduledAt":"2026-05-24T00:22:00"
}

###

### 실패 테스트 (재시도용)

POST http://localhost:8080/notifications
Content-Type: application/json

{
  "receiverId":"민경",
  "message":"실패 테스트",
  "eventId":"PAYMENT_FAIL_001",
  "channel":"EMAIL"
}

###

### 전체 조회

GET http://localhost:8080/notifications

###

### 단건 조회

GET http://localhost:8080/notifications/1

###

### 읽음 처리

PATCH http://localhost:8080/notifications/1/read

###

### 수동 재시도

PATCH http://localhost:8080/notifications/3/retry

###

### 사용자별 조회

GET http://localhost:8080/users/%EB%AF%BC%EA%B2%BD/notifications

###

### 읽음 여부 필터 조회

GET http://localhost:8080/users/%EB%AF%BC%EA%B2%BD/notifications?readStatus=true